## Q0: (0 point) 
- Please install Anaconda on your own PC or the PC in the lab. (Download link: https://www.anaconda.com/download/ )
- Please install related python3 packages: numpy, scikit-learn, jupyter (pip3 install numpy, scikit-learn, jupyter)

## Q1: (100 point) 
Use NumPy module to define and operation the following operations on matrices and vectors. Please readme the following example and answer sub-questions 1-5 in jupyter notebook.

### Example for Q1
#### Question: 
- Calculate the matrix multiplication between random matrix A (shape 4x3) and random matrix B (shape 3x5)

In [1]:
# Answer to example
import numpy as np
# 1. Generate random matrix A and B
a = np.random.random(size=(4, 3))
b = np.random.random(size=(3, 5))
# 2. Execute matrix multiplication and assign the result to matrix C
c = np.matmul(a, b)
# 3. Print the shape and value of C
print(c.shape)
print(c)

(4, 5)
[[1.64952221 1.17609856 1.01491044 1.02684893 0.61445659]
 [0.86065177 0.66977388 0.67663327 0.95392285 0.43529568]
 [1.68961287 1.308003   1.15058003 1.22941972 0.71859307]
 [1.77371655 1.15212874 1.02097768 1.098049   0.60214554]]


### (1) Define NumPy Array
#### Question: 
- Use NumPy to define the following matrix A and vector b, then print A and b
$$
 A = 
 \begin{bmatrix}
   1 & 2 & 3 & 3\\
   4 & 5 & 6 & 1\\
   7 & 8 & 9 & 4
  \end{bmatrix},
   b =
 \begin{bmatrix}
   7 \\
   4 \\
   1 \\
  \end{bmatrix}
$$


In [ ]:
# Answer to sub-question 1

### (2) Basic Mathematical Operation
#### Question:  
- Mulitply scalar3 and substract scalar 6 to each element in A, then print the new result matrix.

In [ ]:
# Answer to sub-question 2

### (3) Broadcast Mechanism
#### Question: 
- Use the broadcast mechanism in NumPy to add b to **each row** of the matrix A, then print the new result matrix.

In [ ]:
# Answer to sub-question 3

### (4) Dimension Manipulation Operation
#### Question: 
- (Slice) Get the first and the third column of the Matrix A to construct a new matrix, then print it.
- (Split) Split the Matrix A to three row vectors, then print them.

In [ ]:
# Answer to sub-question 4

### (5) Matrix Operation
#### Question:
- Execute SVD decompositon to the matrix A, then print the results (unitary matrix and singular value vector).

In [ ]:
# Answer to sub-question 5