## Q0: (0 point) 
- Please install Anaconda on your own PC or the PC in the lab. (Download link: https://www.anaconda.com/download/ )
- Please install related Python3 packages: numpy, scikit-learn, jupyter (pip3 install numpy, scikit-learn, jupyter)

## Q1: (100 point) 
Use NumPy module to define and operation the following operations on matrices and vectors. Please readme the following example and answer sub-questions 1-5 in jupyter notebook.

### Example for Q1
#### Question: 
- Calculate the matrix multiplication between random matrix A (shape 6x3) and random matrix B (shape 3x5)

In [1]:
# Answer to example
import numpy as np
# 1. Generate random matrix A and B
a = np.random.random(size=(6, 3))
b = np.random.random(size=(3, 5))
# 2. Execute matrix multiplication and assign the result to matrix C
c = np.matmul(a, b)
# 3. Print the shape and value of C
print(c.shape)
print(c)

(6, 5)
[[0.75221784 0.42074499 0.85206996 0.21011375 0.85974795]
 [0.79681567 0.61589504 0.50934126 0.16964195 0.69373947]
 [0.42984565 0.27465248 0.52540723 0.1530376  0.50651616]
 [1.34601225 1.40758841 1.14489607 0.59261552 1.27085604]
 [1.01023781 1.4952428  0.64868128 0.60626961 0.79649177]
 [0.25611351 0.67401721 0.34239024 0.3807691  0.25609778]]


### (1) Define NumPy Array
#### Question: 
- Use NumPy to define the following matrix A and vector b, then print A and b
$$
 A = 
 \begin{bmatrix}
   1 & 7 & 3 & 3\\
   4 & 9 & 6 & 1\\
   2 & 8 & 5 & 4
  \end{bmatrix},
   b =
 \begin{bmatrix}
   7 \\
   4 \\
   1 \\
  \end{bmatrix}
$$


In [ ]:
# Answer to sub-question 1

### (2) Basic Mathematical Operation
#### Question:  
- Mulitply a scalar 3 and substract a scalar 6 to each element in A, then print the new result matrix.

In [ ]:
# Answer to sub-question 2

### (3) Broadcast Mechanism
#### Question: 
- Use the broadcast mechanism in NumPy to add b to **each row** of the matrix A, then print the new result matrix.

In [ ]:
# Answer to sub-question 3

### (4) Dimension Manipulation Operation
#### Question: 
- (Slice) Get the first and the third column of the Matrix A to construct a new matrix, then print it.
- (Split) Split the Matrix A to three row vectors, then print them.

In [ ]:
# Answer to sub-question 4

### (5) Matrix Operation
#### Question:
- Execute the SVD decompositon to the matrix A, then print the results (i.e. unitary matrix and singular value vector).

In [ ]:
# Answer to sub-question 5